### ISSUE TITLE
Technical guidance on DNS, targeted to our partners

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#102]
Our [Dec 20, 2019 guild meeting](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94) identified a need that would support partners using Federalist, as well as potential tech leads on a partner engagement:

> Partners need high-level information about DNS, starting from scratch often, low understanding for using Federalist.
> Who to talk to in your org, requirements before going live, best practices, i.e,. “give me a zone file”.
> Similar to compliance/ATO – easy/solved for TTS, but not so for partners who have widely different implementations, need early conversations.

I found this existing page elsewhere at GSA: https://home.dotgov.gov/management/ – @davemcorwin could you check out to see how much of the problem it addresses, and elaborate more on what you think would be useful?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
