### ISSUE TITLE
Add Last Modified datestamp to page template

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#106]
Briefly discussed in 01/31/2020 guild meeting:
As a reader of the guide, I want to easily determine how recently a particular page has been updated, as an indicator of relevancy.

**Comment by ryanhofdotgov** [comment]
Existing uswds-jekyll mechanism does not work on Federalist due to shallow checkout done there. [Relevant Slack thread](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1565804388080700).

**Comment by ryanhofdotgov** [comment]
Federalist just got new feature that will allow  jekyll-last-modified-at to work! 
https://federalist.18f.gov/documentation/federalist-json/

**Comment by Sgtpluck** [comment]
Closing because this handbook is being merged into the TTS handbook, rendering it moot.

**Comment by mahmod87** [comment]
.
