### ISSUE TITLE
Replace the default homepage text

### ISSUE THREAD

**Issue by brittag** [18F/development-guide#11]
The [Engineering team intro in the handbook](https://handbook.18f.gov/engineering) links to this best practices guide, but the [guide homepage](https://pages.18f.gov/development-guide/) is the default text. It'd be great to update that homepage (even with just basic info) to avoid confusing newcomers checking out this guide. :)

**Comment by jessieay** [comment]
Updated in https://github.com/18F/development-guide/pull/20

Closing! :)
