### ISSUE TITLE
Should we link to repos that have been archived

### ISSUE THREAD

**Issue by saracope** [18F/development-guide#119]
The **Initialization Checklist** section of the [project setup](https://engineering.18f.gov/project-setup/) page links to [18f init](https://github.com/18F/18f-scaffolding#18f-init) which has been archived. 

Should links to archived repos be removed?
Should we be checking for archived repo resources and ask that they be unarchived?

**Comment by ryanhofdotgov** [comment]
Addressed by #149 – yeah, we shouldn't link to any unmaintained repos
