### ISSUE TITLE
Remove Hound recommendation - replace with Code Climate?

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#122]
From: https://github.com/18F/frontend/issues/183
Hound is recommended here: https://frontend.18f.gov/#on-github-with-hound

I'm pretty sure Hound is not on the approved SaaS list. The recommendation could maybe be replaced with Code Climate (which is also a nice tie-in to the Before You Ship guide: https://before-you-ship.18f.gov/security/static-analysis/).

**Comment by aduth** [comment]
Related: #162

(On the topic of considering CodeClimate as an alternate recommendation)
