### ISSUE TITLE
Update Accessibility guidance

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#123]
Had 2 folks across TTS mention the quality/utility issues of https://engineering.18f.gov/accessibility-scanning/ in past week – seems like a good place to start a sweep of content updates on.

Desirable qualities:
* Uses up-to-date open source projects and standard TTS tooling (e.g., docker, not vagrant).
* Ideally, something we can refer to in a QASP and (semi-)automate with CI/CD tools.

**Comment by ryanhofdotgov** [comment]
Relevant comments from today's Accessibility/DevOps guild meeting:

* At Login we're working on increasing our accessibility code coverage using a tool called aXe which scans pages for 508/WCAG A and AA, here are some examples:
https://github.com/18F/identity-idp/tree/master/spec/features/accessibility
* Here's an example of how simple the aXe tests can be: https://github.com/18F/identity-idp/blob/master/spec/features/accessibility/static_pages_spec.rb
* https://www.deque.com/axe/, https://github.com/dequelabs/axe-core
* You can also tell pa11y-ci what runner you want it to use. Like axe or html code sniffer: https://github.com/pa11y/pa11y-ci

**Comment by aduth** [comment]
The 18F Accessibility Guide also includes relevant resources, both on the homepage ("Testing Tools") and under the Tools subpage:

- https://accessibility.18f.gov/
- https://accessibility.18f.gov/tools/

The latter includes a subsection about automated testing.

It could be worth considering to either add links to these resources, or consolidate them.

**Comment by ryanhofdotgov** [comment]
Also: https://accessibility.civicactions.com/posts/automated-accessibility-testing-leveraging-github-actions-and-pa11y-ci-with-axe

**Comment by Sgtpluck** [comment]
Closed with #250
