### ISSUE TITLE
Add initial recommendations on GitHub Actions

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#128]
Synthesize comments from guild meeting here:
https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit#bookmark=id.f0zqx731rqd1

Update CI/CD sections on:
https://engineering.18f.gov/continuous-deployment/
https://engineering.18f.gov/project-setup/
https://engineering.18f.gov/workflow/
https://engineering.18f.gov/integrations/

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
