### ISSUE TITLE
Make mention of audit function in Chrome DevTools

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#132]
New in Chrome DevTools as of January 2020:
https://developers.google.com/web/updates/2017/05/devtools-release-notes#lighthouse

"The Audits panel is now powered by Lighthouse. Lighthouse provides a comprehensive set of tests for measuring the quality of your web pages."

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
