### ISSUE TITLE
Two suggested corrections

### ISSUE THREAD

**Issue by jadudm** [18F/development-guide#135]
Combining, because these two fixes are small.

* In [_pages/integrations.md](/18F/development-guide/blob/master/_pages/integrations.md), "attain" -> "attaining" as a grammatical change.
* In [_pages/project-setup.md](/18F/development-guide/blob/master/_pages/project-setup.md), remove waffle.io link (service no longer exists).

I have [made these changes in a fork](https://github.com/18F/development-guide/compare/master...jadudm:master) and can submit a merge request if desired.

**Comment by ryanhofdotgov** [comment]
Thanks @jadudm!
