### ISSUE TITLE
Revisit color scheme used with classification labels

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#146]
Now that we've added a caution tag, it may be useful to get some design input on the color scheme associated with our labels. Current scheme:
<img width="579" alt="Screen Shot 2020-04-13 at 10 57 25 AM" src="https://user-images.githubusercontent.com/37100189/79146208-db796380-7d76-11ea-97af-597d6bc9e898.png">

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
