### ISSUE TITLE
Classification tags for headings, lists/tables

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#147]
The current classification tags for requirement, standard, default, etc. don't work so well when used to describe a bulleted/numbered list or a table:
- Those uses need a plural form (e.g., Requirements, Defaults)
- Style (size/layout) for those other use cases aren't optimal

Current work around is to not use the tags at all (e.g., `## Requirements`)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
