### ISSUE TITLE
frontend guides lead to 404 errors

### ISSUE THREAD

**Issue by skorasaurus** [18F/development-guide#151]
Hi, 
Thanks for the work that you do; the guides have been very helpful in my development in establishing our own best practices that I wrote at the [Cleveland Public Library](https://cpl.org/web-standards/). 

I just wanted to let you know, in case you weren't already aware, 
that several of the 18F URLs relating to the frontend aren't properly being redirected and result in 404 errors. 

Some example URLs include: 
https://frontend.18f.gov/css/naming/
https://engineering.18f.gov/frontend/

As I understand, [the frontend guide](https://github.com/18F/frontend) has been folded into this repository so I've made the

**Comment by ryanhofdotgov** [comment]
@skorasaurus Appreciate the heads up – thank you!
