### ISSUE TITLE
Address 1-dev teams and code reviews

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#153]
Take a stab at writing up the issue of code review practice in the context of 1-dev teams that are fairly common at TTS, whether on an engagement or a small-ish product.
- reach out to #dev for PRs
- downsides: reviewers don't have context, works well when there is a smaller chunk that you really want feedback on

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
