### ISSUE TITLE
Add section on cache control headers

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#178]
## Background information

Web applications often deliver all their content, not just static resources, via a Content Distribution Network (CDN). For example, on cloud.gov with AWS CloudFront via the [External Domain Service](https://cloud.gov/docs/services/external-domain-service/) or the deprecated [CDN service](https://cloud.gov/docs/services/cdn-route/).

This can result in per-user session cookies and private user data transiting the CDN. If there is not careful attention to setting the `Cache-Control` header with an appropriate value (e.g., `no-store`, `private`), the CDN can cache cookies and private data and deliver it to clients that should not possess it.

As local development and staging environments don't always incorporate a CDN or CDN work-a-like (e.g., [Varnish Cache](https://varnish-cache.org/intro/)), cache control defects might only appear once an application gets production use. 

Other notes:
* Cache-Control will affect both caching at the CDN, as well as at the browser. It is important to make sure the value chosen is appropriate for both.
* [IE11 potentially interprets/ignores Cache-Control values differently](https://stackoverflow.com/a/40613321) than Chrome, Firefox, etc. Guidance in this handbook should ideally address those needs.

Useful references:
* https://fideloper.com/cloudfront-full-site-delivery
* https://carvesystems.com/news/web-cache-session-hijacking/
* https://web.dev/http-cache/ (especially decision flowchart at bottom of page)

## User stories

As a web application developer at TTS, I want specific guidance and checklists in this guide concerning caching headers, CDNs, and security, in order to decrease the risk that TTS ships production code that exposes private user data and session information. 

## Acceptance criteria

- New page that addresses content area 
- Updated menu links

**Comment by afeld** [comment]
Transferred it for ya 😉

**Comment by pburkholder** [comment]
Tracking this, as we should link to it as a resource on the cloud.gov CloudFront documentation as a service to our customers.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
