### ISSUE TITLE
Ruby guide "recommended Rubocop configuration" is 404

### ISSUE THREAD

**Issue by aduth** [18F/development-guide#179]
**Steps to reproduce:**

1. Navigate to https://engineering.18f.gov/ruby/
2. Click "recommended Rubocop configuration"

_Expected:_ See configuration
_Actual:_ 404

**Debugging:**

The page is generated to the expected path, but likely because it's prefixed with `.` is treated as a hidden file and not publicly available (?)

**Possible solutions:**

- Omit leading `.`
- Change "recommended Rubocop configuration" to point to the GitHub source file
   - If chosen, should the file be moved somewhere more appropriate

**Comment by ryanhofdotgov** [comment]
Thanks! Looks like it is a limitation of the Federalist mechanism for publishing to S3, [it ignores all dotfiles except for .well-known/security.txt](https://github.com/18F/federalist-garden-build/blob/b24058d2ea1e05a43e7444b8d5ab98b4d12b42a4/src/publishing/s3publisher.py#L104). The file is correctly served locally (and is explicitly included in `_config.yml`). I'll implement one of those work-arounds.

**Comment by ryanhofdotgov** [comment]
Resolved in #190
