### ISSUE TITLE
Document Dependabot best practices

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#182]
- [ ] Write up consensus from discussion from [Guild meeting](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit#) and [Slack thread ](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1597430473392000).
- [ ] Provide sample Dependabot configuration file.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
