### ISSUE TITLE
Write up recommendations for vendor forks vs protected branches

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#183]
Guidance on how to manage assisted acqs repositories:
[Slack thread](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1597945325002000)
[Guild notes](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit#)

18F-centric discussion so far, see if CoEs have any thoughts.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
