### ISSUE TITLE
Update programming language selection guide

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#187]
See:
* [Sep 11th notes from Guild meeting](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit)
* [Slack survey responses](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1599830381115400)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
