### ISSUE TITLE
Link to this guide from https://pages.18f.gov/guides/ ?

### ISSUE THREAD

**Issue by toolness** [18F/development-guide#19]
I noticed that this guide isn't linked-to from https://pages.18f.gov/guides/.  Should it be?

Note that I'm wary of doing this until #18 is merged, because the front page of our guide is currently quite confusing.

**Comment by jessieay** [comment]
We just merged https://github.com/18F/development-guide/pull/20 which moves this away from being a "guide" repo and makes it more of just a repo with markdown. Hopefully that makes it easy for people to read / update content on GH.

It does mean, however, that this is no longer going to work as a "guide" on that page. 

Closing this issue. Thanks for opening, @toolness !
