### ISSUE TITLE
Clean up URLs under nav sections

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#198]
#196 implements some basic structure to the content. However, all the original URLs were preserved, so the primary nav isn't highlighted when a sub-topic is navigated to.

Add redirects using jekyll-redirect-from. Also identity and resolve any dangling pages (e.g., https://engineering.18f.gov/frontend/) and add redirects as required.

**Comment by ryanhofdotgov** [comment]
Related to #199

**Comment by Sgtpluck** [comment]
Closed with #236
