### ISSUE TITLE
Merge content under (JavaScript, CSS) directories into single pages

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#199]
uswds-jekyll sidenav only handles 3 levels of topics, with the 3rd level anchors on a page at the 2nd level. The JavaScript and CSS content from the front end guide doesn't fit this, so the primary/sidenav for those topics is inconsistent with the rest of the site.

Quick fix is to merge all the JavaScript pages into one page, likewise with CSS. Use jekyll-redirect-from to redirect appropriately.

**Comment by Sgtpluck** [comment]
closed with #235
