### ISSUE TITLE
add documentation about broken link checking

### ISSUE THREAD

**Issue by afeld** [18F/development-guide#205]
https://gsa-tts.slack.com/archives/C03EMDS6P/p1603206455202900

**Comment by Sgtpluck** [comment]
18F guides use [htmlproofer](https://github.com/gjtorikian/html-proofer) to check internal links. Add recommendation to use that for projects that use ruby

https://github.com/18F/isildurs-bane/blob/main/Rakefile

Also check in with [site-scanner folks](https://gsa-tts.slack.com/archives/CJ9JT2F2T) -- they used puppeteer to similar effect.

**Comment by adborden** [comment]
FYI, you can also [use htmlproofer to test **external** links](https://github.com/GSA/resources.data.gov/blob/main/package.json#L44), too.

**Comment by Sgtpluck** [comment]
@adborden that's a good point, although the thread mentions some difficulties in CI with external links, so those possible pitfalls should be documented here as well!

**Comment by Sgtpluck** [comment]
Closed with #306
