### ISSUE TITLE
Add guidance/lessons on lightweight apps using "low-code" tools

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#210]
There's been a few different projects that have used low-code tools like Google Sheets/AirTable/Smartsheet to effectively build out prototypes as well as fully-functional applications.

TTS Engineering would benefit from a write-up that had insights on:
- size/scope of problem where these tools make sense
- any restrictions regarding data (e.g., PII, etc.) and leveraging ATO at TTS
- incorporating them into a Federalist site, cloud.gov, etc.

Examples include:
* @ryanwoldatwork's [Wardley mapping demo given in Oct 9th engineering practices meeting](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit#heading=h.hel9i8xq91dz)
* @apburnes, et al [State Ops Center presentation](https://docs.google.com/presentation/d/11uvKVyct6bD9VRJc6Lk5bq8lV7Yppozs_NMUvqjoB3A/edit#slide=id.g5ecdbbee9e_0_34), [18F/dos-ops-center](https://github.com/18F/dos-ops-center)
* @lauraGgit's [Google Sheet -> GitHub ](https://gsa-tts.slack.com/archives/CBA948FR9/p1535485007000100), [google-sheets-script.gs](https://github.com/18F/fedramp-data/blob/master/scripts/google-sheets-script.gs)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
