### ISSUE TITLE
"Edit this page" links are broken

### ISSUE THREAD

**Issue by mchelen-gov** [18F/development-guide#213]
1. Go to https://engineering.18f.gov/
1. Click "Edit this page"
1. URL `https://github.com/18F/development-guide/edit/main/_pages/index.md` does not exist

**Comment by ryanhofdotgov** [comment]
Thanks! Note: dependent on upstream template issue: https://github.com/18F/isildurs-bane/issues/36

**Comment by ryanhofdotgov** [comment]
Resolved in [upstream guide template](https://github.com/18F/isildurs-bane/issues/36) and merged here
