### ISSUE TITLE
Add blurb about contributing

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#215]
Add a blurb to the effect of:
"Getting new practices into the guide is pretty light on process –Someone usually digs up some consensus via Slack or a guild meeting, they write up the doc in a PR and ask for the guild leads for review. If you think a proposal might be controversial after getting some consensus prior, can also post the draft PR to #dev (and elsewhere if you don’t think target audience is in that channel)."

Add to README and then also somewhere in the About guide section on published website.

**Comment by Sgtpluck** [comment]
I've got a few minutes so I hope you don't mind that I snagged this @ryanhofdotgov

**Comment by ryanhofdotgov** [comment]
Not at all! Any self-assignments to issues were very optimistic and a form of self accountability that failed 😅

**Comment by Sgtpluck** [comment]
Closed with #233
