### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#222]
Previous iterations of guide had a table of content on the front page, but was left at the wayside as we adopted uswds-jekyll and mirrored the structure of the UX guide. Based on feedback, bring this back to the front of the site. 

Implementation notes:
* Auto-generate ToC from the same YAML files that populate the menus, see if we can implement at uswds-jekyll level for resuse.

**Comment by Sgtpluck** [comment]
@ryanhofdotgov is this still reasonable work with the handbooks all merging together or should we close this issue?

**Comment by ryanhofdotgov** [comment]
Yeah, I agree. Anything to do with styling, layout, easier discoverability, etc. should be closed.
