### ISSUE TITLE
Add guidance on big-bang releases.

### ISSUE THREAD

**Issue by adunkman** [18F/development-guide#230]
We like to advocate for slow rollout releases over big-bang releases. That’s probably something we’d like to document somewhere, but is out of scope for this issue. 

Instead, we often find ourselves working in projects which, for reasons we cannot control and against our advice, are scheduled for a big-bang release.

I think we’ve learned some things which we should pass on about this release strategy.

**Comment by afeld** [comment]
Shout-out to [Hello, Production](https://blog.thepete.net/blog/2019/10/04/hello-production/).

**Comment by ryanwoldatwork** [comment]
https://dzone.com/articles/monolith-to-microservices-using-the-strangler-patt

**Comment by adunkman** [comment]
Just wanted to loop back to the original issue: 

> We like to advocate for slow rollout releases … [it] is out of scope for this issue.

Strategies that reduced stress and helped the US Tax Court with their big-bang release: 

- Release to different user groups at different times — namely, internal users first, then the public. This allowed customer support and bug fixing to focus on specific user groups and tasks. The US Tax Court separated the releases by a week.
- Give yourself a lot of time — the US Tax Court set the expectation that the old system would go offline about 2 months before promising the new system would come online. This gave the team plenty of time to adjust as critical issues were discovered, and required contingency planning on alternative strategies to keep the court functioning without the software system, which reduced the overall stress of the release (there was a plan B, despite it being painful).

**Comment by Sgtpluck** [comment]
@adunkman notes taken during the guild meeting [are here](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit#bookmark=id.1q2e66qb5pxi).

@mheadd also identified a need (that is documented in #232) for identifying factors that encourage big bang releases and coming up with strong ways to mitigate them -- we [started a spreadsheet for that info](https://docs.google.com/spreadsheets/d/1yqILGiNj1DbCQCcSmMLwI4R2nkyuunzHy70dZ-8YCXE/edit?usp=sharing).

Were you interested in writing this stuff up? Did you want help with that?

**Comment by adunkman** [comment]
I am interested in writing it up, and it’s a bit down my list. I’ll keep this issue updated and likely knock it out in one go — so if there isn’t a linked PR here, I haven’t started it yet.

If anyone else beats me to it, go for it! :)

**Comment by Sgtpluck** [comment]
Closed with #257
