### ISSUE TITLE
where to find a list of agencies

### ISSUE THREAD

**Issue by afeld** [18F/development-guide#249]
## Background information

This seemingly simple question comes up every once in a while — would be useful to speak to where to find definitions/list(s).

- https://open.gsa.gov/api/fh-public-api/
- https://www.usa.gov/federal-agencies/
- https://www.usaspending.gov/agency / https://api.usaspending.gov/api/v2/bulk_download/list_agencies/
- https://www.federalregister.gov/agencies / https://ecfr.federalregister.gov/agencies

## Implementation step

- [x] Determine what is authoritative source

## Acceptance criteria

- [x] TTS has / points to written guidance on how to define and how to get a machine-readable list of agencies (for drop-downs in forms, etc.)

**Comment by vdavez** [comment]
There's a thing that SAM.gov maintains called the Federal Hierarchy, which AFAIK is pretty much canonical. https://beta.sam.gov/help/federal-hierarchy

**Comment by afeld** [comment]
[How to Define an "Agency" deck from 2019](https://docs.google.com/presentation/d/187rlenZuGI8KXeIsnoWjJ7jOx2uA77FOlD1R04XoTl8/edit?ts=607f25f7#slide=id.p1)

**Comment by afeld** [comment]
[Research on Canonical Federal Entity IDs](https://docs.google.com/document/d/1vsusqxsgHqFhzaHSOXrTJ7sF3IN7LGZVFNNM3m66i4w/edit) via @JJediny

**Comment by josephderosales** [comment]
Email sent to Charlene Blanco from USAGov program to hopefully provide some insight/details.

**Comment by josephderosales** [comment]
Follow up email sent - awaiting response from Charlene. Moving to blocked

**Comment by josephderosales** [comment]
Authoritative Source:

https://usagov.platform.gsa.gov/usaapi/api/v1/usagov/directory_records/federal.json

**Comment by josephderosales** [comment]
@afeld I couldn't find an appropriate section in the TTS Handbook to update, so instead I created a reference doc that you can share (or retrofit in the handbook).

Feel free to update/modify as you see fit.

https://docs.google.com/document/d/1za-yxSzjYehqf3CxkA7yssJ5fTSOv5BXo3B1jid-Szs/edit#heading=h.f1halm19z9v
