### ISSUE TITLE
Adopt USWDS Identifer, replacing UX guide's Anchor

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#261]
This template adopted the UX guide's work, and that implemented a pre-release USWDS component called an Anchor (at the time). This later became [Identifier](https://designsystem.digital.gov/components/identifier/) once it was officially released. 

The USWDS footer (at least in in the Jekyll template) wasn't designed to work with it exactly, so that lead us to the footer fork you see here. See how we can preserve the styling we adopted from the UX guide, keep the Edit page/last modified date functionality, but get rid of the Anchor-driven fork.

**Comment by Sgtpluck** [comment]
@ryanhofdotgov since we import the uswds-jekyll does this need to be fixed in the actual template? (i see that they removed identifier [~8 months ago](https://github.com/18F/uswds-jekyll/commit/b2d6921a43b4ee34730f300b6863cbfee343b69e), not sure why.)

**Comment by ryanhofdotgov** [comment]
Ah, yes – I think that's right.

Digging into the related PR, there was some [initial discussion on the product vision for the theme](https://github.com/18F/uswds-jekyll/pull/210#discussion_r494538416).

[Here's a separate PR where that conversation continued.](https://github.com/18F/uswds-jekyll/pull/212#issuecomment-699038650)

**Comment by Sgtpluck** [comment]
Closing because this handbook is being merged into the TTS handbook, rendering it moot.
