### ISSUE TITLE
Default branches on new repos should be named 'main'

### ISSUE THREAD

**Issue by dylanirlbeck** [18F/development-guide#266]
On the few repos I've seen (/handbook and /tts-tech-portfolio, for example), the default branch appears to be `master`. In order to abide by the Diversity, Equity, and Inclusion principles laid out in [the handbook](https://handbook.tts.gsa.gov/diversity/), I believe the development guide should recommend a default branch name of `main` for all current and new repos.

I also believe some work should be scoped to rename the branches of other repos, but I'm not quite sure the best place to open issues (I was thinking each individual repo, but I'm open to suggestions).

**Comment by ryanhofdotgov** [comment]
I think this should already be happening – [here's the Slack thread](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1598535034055200) from when this change was made in the 18F org in GitHub.

There's probably still a few references to `master` in older content in guides that could be updated though.

**Comment by dylanirlbeck** [comment]
Got it, thanks for the info @ryanhofdotgov. It is likely unnecessary to include anything about the default branch in the development guide if the setting is configured at an org-level. I think it would be helpful to at least open an issue in a given repo if it needs to change its default branch, but there isn't any work for the Development Guide.
