### ISSUE TITLE
"Before You Ship" link no longer works on release-strategies.md

### ISSUE THREAD

**Issue by annepetersen** [18F/development-guide#302]
Not a full issue here: just wanted to flag it to someone's attention.

**Comment by echappen** [comment]
In production, this link redirects to the [Launching Software section of the TTS Handbook](https://handbook.tts.gsa.gov/#launching-software), which I believe is where the Before You Ship guide now lives. Maybe we could update the name of this link in this guide to "Launching Software" to make that connection more apparent.

**Comment by Sgtpluck** [comment]
Closed with #303
