### ISSUE TITLE
Adding example projects & scaffolding links

### ISSUE THREAD

**Issue by rememberlenny** [18F/development-guide#41]
# What

How does everyone feel about a list of "example" projects that have a good project setup structure?

## Example

Python, Ruby, Node.js, Go project lists/links

**Comment by rogeruiz** [comment]
it might be cool to cross-streams here and put things in here =>

https://github.com/18F/cf-hello-worlds

**Comment by cmc333333** [comment]
Agree that this would be great. I'd like to get some (maintained) templates in the future, but in the meantime, if we can highlight existing poster children, we should.

**Comment by tbaxter-18f** [comment]
I'd like to see this be a list of links to project scaffoldings

**Comment by ryanhofdotgov** [comment]
Closing, since after 4 years we are unlikely to get any guide contributions on this topic.

**Comment by tbaxter-18f** [comment]
I kinda forgot this existed, but I think we've at least got some good federalist templates we could highlight. My intention at one point was to build a good Django scaffolding, but we really haven't had enough call for it.
