### ISSUE TITLE
[nodejs] How do I avoid long relative require paths?

### ISSUE THREAD

**Issue by adborden** [18F/development-guide#56]
> What’s the recommended way to load local modules from elsewhere in my node app? (i.e. how do I avoid the `require("../../../some/other/module/I/wrote")` problem)
> I ask because I just fell in this hole and I can’t get out: https://gist.github.com/branneman/8048520

cc @yozlet

**Comment by adborden** [comment]
Some discussion too https://gsa-tts.slack.com/archives/C032KSPPQ/p1494453115332351

**Comment by tbaxter-18f** [comment]
@mgwalker do you have any thoughts on this?

**Comment by mgwalker** [comment]
Not really anything to add to the Slack conversation. I think [Aaron's comment there](https://gsa-tts.slack.com/archives/C032KSPPQ/p1494456658957044) is an important one, re: code organization.  In a fairly large Node/React project I'm working on now, our deepest path traversal is only two levels (`../../module`). If I had to go another level, I'd be thinking about how to restructure the code to make more sense.

[Roger's comment about multiple `package.json`s](https://gsa-tts.slack.com/archives/C032KSPPQ/p1494459066305706) is also really cool and now I want to try it, but I don't want to rip up a bunch of code over it.  😛

**Comment by ryanhofdotgov** [comment]
Closing, since after 4 years we are unlikely to get any guide contributions on this topic.

**Comment by aduth** [comment]
Similar to the idea mentioned earlier with `package.json`, this can also be a good use-case for Yarn / NPM (v7+) workspaces, where one can refactor common, "far-away" utilities as standalone packages.

- https://classic.yarnpkg.com/en/docs/workspaces/
- https://docs.npmjs.com/cli/v7/using-npm/workspaces
