### ISSUE TITLE
Code Review Review

### ISSUE THREAD

**Issue by jessieay** [18F/development-guide#6]
via Slack / @cmc333333 :+1: 

> I have a hair brained scheme for improving code reviews with soft power. It'd go something like this: anyone from this group interested break into teams of two. Each pair would select a project that neither are a part of to study. For the next month, the pair would observe and interact with that project team around code reviews, hopefully improving the project's process and bringing back good ideas to this group. I think the schedule'd fall something like
> Week 1: introduce to team, get their okay for participation, begin interview team members, follow repos
> Week 2: continue interviews, continue following repos, begin asking questions of reviewers around specific PRs (rather than the more general interviews)
> Week 3: begin providing specific feedback, suggestions, etc. around reviews
> Week 4: continue specific suggestions, expanding into higher level concerns in present; writeup/discussion of lessons learned to share with the wider group

Current volunteers are me, @micahsaul, @arowla, @cmc333333, @jmcarp, @pkarman, @monfresh 

@pkarman and @cmc333333 are working with cloud.gov
@arowla and I are on eregs

other teams: 

@micahsaul and @jmcarp 
@monfresh 

If people can update what they are reviewing or if others would like to help out with this mission, feel free to chime in here or on Slack in #wg-code-reviews

I am posting this here for posterity / transparency

**Comment by tbaxter-18f** [comment]
Closing because everyone involved is gone and I have no context for what the plan was.
