### ISSUE TITLE
How do i get started?

### ISSUE THREAD

**Issue by knightcube** [18F/development-guide#68]
I want to get a brief overview of what this project contains actually? I want to see if i can contribute in any way. Languages that i use are java and python. So is there any way i can make any contribution in this repository? Also ,i think the readme should contain a proper summary of the repository.

**Comment by cmc333333** [comment]
Hi @knightcube, this is a documentation repository, not a software project. What do you think is missing from the readme in the root of the repo that'd help explain that better?

**Comment by knightcube** [comment]
Oh alright....so since there are guides for languages in the readme, i didnt find any kind of guide for Java. So i thought if there could be one guide for Java as well it might be helpful.

**Comment by cmc333333** [comment]
Thanks for the thought, @knightcube, but we [tend](https://github.com/18F/development-guide/tree/master/language_selection#our-strongest-languages) to write in Python, Node, and Ruby. We haven't worked on enough Java projects to create new standards, if that makes sense. If you're looking for somewhere to get started, though, I'd recommend looking at the guides from [Apache](https://portals.apache.org/development/code-standards.html), [Google](https://google.github.io/styleguide/javaguide.html), and [Twitter](https://github.com/twitter/commons/blob/06905dc0f1a26440a79ff1164831c85ce2d1bdf0/src/java/com/twitter/common/styleguide.md). We generally try to extend solid, existing standards.
