### ISSUE TITLE
Code Review Project Questions

### ISSUE THREAD

**Issue by ccostino** [18F/development-guide#8]
This is a set of questions intended to be asked of other fellow 18F employees who are working on a variety of projects in order to get a better sense of how code reviews are currently conducted and the role they play.  @micahsaul and I pieced these together in preparation of asking folks in the FEC project.

Please feel free to contribute in order to help improve them!
- How do you perform a code review, what steps do you usually take?
- What do you usually look for in a code review?
- Do you solicit code reviews, or does the team just actively look for them?
- Does the team utilize style guides or has it considered using them in conjunction with linters?
- If there are already some guidelines, does the team adhere to them routinely, and how well have they worked in practice?
- Does the team make use of code coverage tools?  If so, which ones and how?
- Is there any automation/continuous integration setup with the projects the team works on?

**Comment by ccostino** [comment]
After conducting a couple of the interviews today I've noted a couple of areas of improvement for asking questions and have updated them below.  Prior to asking specific questions though, we should also make sure that we begin with asking the participant if they are familiar with the purpose of the interview and provide a brief introduction to wg-code-reviews, the purpose behind this particular exercise, and the goals we aim to achieve.

* Does your team perform code reviews?  *Note:  If the answer is no, modify the questions to focus on the hypothetical case of performing code reviews and what potential benefits and downsides there might be to instituting them on the team.*
* Could you talk about how you perform a code review?
 * What steps do you take?
 * What do you specifically look for while reviewing code?
* Does your team solicit code reviews when the work is ready, actively monitor new work that needs to be reviewed, or some combination thereof?
* Does your team utilize style guides?
 * If so, how does this work in practice?  Does the team adhere to them consistently or no?
 * If not, has your team ever considered using them?
* Does your team make use of any tools to aid in code reviews?
 * If so, which ones and how?
 * If not, has your team considered using any tools, e.g., code coverage indicators or linters?
* Does your team make use of any testing or test frameworks?
* Does your team have any automation/continuous integration setup?
* Are there any areas of code reviews on your team that you find work exceptionally well in your team?
* Are there any areas of code reviews on your team that you find are counter-productive and would like to either see eliminated entirely or receive suggestions for improvement?

**Comment by tbaxter-18f** [comment]
Closing due to age.
