### ISSUE TITLE
Add Github DNS info

### ISSUE THREAD

**Issue by mgwalker** [18F/development-guide#82]
It might be worth adding to the guide somewhere how to work with Github through a DNS outage, by temporarily updating your `~/.ssh/config` to include:

```
Host github.com
    Hostname 192.30.253.122
    Port 443
```

Slack convo: https://gsa-tts.slack.com/archives/dev/p1477072057001255
More info: https://news.ycombinator.com/item?id=12763089

(From https://github.com/18F/laptop/issues/85, originally https://github.com/18F/handbook/issues/53)

**Comment by adborden** [comment]
I don't think this is necessary. We should use DNS as it's meant to be used and in the exceptional event of a major outage, I think it's fine to spread the work-around via word of mouth or by public service announcement.

Hard coding the IPs would be a temporary fix anyway. GitHub has several IPs and can swap them out at anytime.

**Comment by tbaxter-18f** [comment]
Closing for reasons outlined above. I just hope we remember this when we need it!
