### ISSUE TITLE
Implement search function, similar to TTS handbook

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/development-guide#98]
As a reader of this guide, it would help to have a visible, intra-guide search function.

The guides listed on https://18f.gsa.gov/guides/ have mixed support for intra-guide search. Some don't have it, some use a Jekyll plug-in (and presumably static JSON exported to `_site`).

At first glance, the best approach seems to be used in the [TTS handbook](https://handbook.18f.gov/) – it uses a widget connected to search.usa.gov. See their [_config.yml](https://github.com/18F/handbook/blob/666a34f8347e5f372eca1215c9e6a14a9e8fd72f/_config.yml#L47) as a starting point.

**Comment by eddietejeda** [comment]
You may want to look at how we setup search.gov as an API call and display results inline with JavaScript here https://github.com/18F/federalist-uswds-jekyll

**Comment by afomi** [comment]
@ryanhofdotgov - this feature requires a Search.gov account. Is Search.gov account information for this dev guide available?

**Comment by ryanhofdotgov** [comment]
@afomi – no, no search.gov account for the dev guide as of yet. I think this will be new ground.

**Comment by ryanhofdotgov** [comment]
Resolved by #194
